import {supabase} from './supabase';
export type DeviceRole='pos'|'scanner';
export type RegisterMessage={type:'barcode';barcode:string;sourceId:string;sentAt:number};
const ROLE_KEY='yn-device-role',REGISTER_KEY='yn-register-code';
const deviceId=()=>{let v=localStorage.getItem('yn-device-id');if(!v){v=crypto.randomUUID();localStorage.setItem('yn-device-id',v)}return v};
export const getSavedDeviceRole=():DeviceRole|null=>{const v=localStorage.getItem(ROLE_KEY);return v==='pos'||v==='scanner'?v:null};
export const setDeviceRole=(v:DeviceRole)=>localStorage.setItem(ROLE_KEY,v);export const getRegisterCode=()=>localStorage.getItem(REGISTER_KEY)||'';export const setRegisterCode=(v:string)=>localStorage.setItem(REGISTER_KEY,v);export const makePairCode=()=>`YN-${Math.floor(1000+Math.random()*9000)}`;const channelName=(c:string)=>`yn-pos-register-${c.toUpperCase()}`;
export function subscribeToRegister(code:string,onMessage:(m:RegisterMessage)=>void,onConnected?:()=>void,onDisconnected?:()=>void){if(!supabase||!code)return()=>{};const c=supabase.channel(channelName(code),{config:{broadcast:{self:false}}});c.on('broadcast',{event:'barcode'},({payload})=>{const m=payload as RegisterMessage;if(m?.type==='barcode'&&m.sourceId!==deviceId())onMessage(m)});c.subscribe(status=>{if(status==='SUBSCRIBED')onConnected?.();if(status==='CLOSED'||status==='CHANNEL_ERROR'||status==='TIMED_OUT')onDisconnected?.()});return()=>{void supabase.removeChannel(c)}}
export async function sendBarcode(code:string,barcode:string){if(!supabase||!code)return;const c=supabase.channel(channelName(code),{config:{broadcast:{self:false}}});await new Promise<void>(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};c.subscribe(async status=>{if(status==='SUBSCRIBED'){await c.send({type:'broadcast',event:'barcode',payload:{type:'barcode',barcode,sourceId:deviceId(),sentAt:Date.now()}});finish()}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){finish()}});setTimeout(finish,3000)});void supabase.removeChannel(c)}
